### ISSUE TITLE
Some improvement ideas

### ISSUE THREAD

**Issue by ngryman** [vdemedes/gifi#10]
A quick list of improvements that could be nice:
- [ ] Set all images to the same size, preferably to `$COLUMNS` if available.
- [ ] Link to _gify_ if we like a particular one. I don't know if it's possible.
- [ ] Display `npm` summary when install has finished.
- [ ] Display some sort of progress interleaved with gifs in some way.

**Comment by vadimdemedes** [comment]
I appreciate your time & effort, but these improvements go way beyond the scope of this project, which is kind of just a joke tool :)

**Comment by ngryman** [comment]
I understand :)

Thing is, I'm installing a sh**load of stuff lately. So for me it's not a toy, but a true relief! :laughing:
More seriously I find the idea of sindre awesome, and your project too. It deserves to be a first class toy.

I think normalizing image sizes and displaying the end summary would make this perfect.
Would you be interested in some PRs?

**Comment by vadimdemedes** [comment]
Absolutely, PRs are always welcome :)
