### ISSUE TITLE
Opens gifs in browser

### ISSUE THREAD

**Issue by altaywtf** [vdemedes/gifi#11]
**os:** os x 10.11.3
**shell:** zsh (with oh-my-zsh)
**term:** xterm-256color
**npm version:** 3.3.12
**node version:** 5.4.1

![screen shot 2016-02-27 at 20 52 30](https://cloud.githubusercontent.com/assets/9790196/13374666/0f015ffa-dd94-11e5-97c3-8361ab0e99a9.png)
![screen shot 2016-02-27 at 20 52 34](https://cloud.githubusercontent.com/assets/9790196/13374667/0f05b7da-dd94-11e5-8abb-d0e370261c07.png)

**Comment by vadimdemedes** [comment]
If you are not using iTerm (which is the only terminal that supports images), gifi will open GIFs in browser instead.
