### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by donlion** [vdemedes/gifi#12]
MacBook Pro (Retina, 13-inch, Late 2013)

<img width="397" alt="screen shot 2016-02-28 at 22 17 36" src="https://cloud.githubusercontent.com/assets/2965242/13381947/25e6fbaa-de69-11e5-8243-d5f415c13262.png">

**Comment by zckrs** [comment]
You need NodeJS >= v4.

Nice work @vdemedes

**Comment by casmith** [comment]
Agreed, I solved this by upgrading from 0.12.x to 4.x.

**Comment by vadimdemedes** [comment]
I'll leave this as a request to make it compatible with older Node.js (v0.10, 0.12). Thanks for reporting!

**Comment by creeperyang** [comment]
@vdemedes Seems no more `ES2015` features used besides `const/let`. So it is okay to use `var` only.

**Comment by vadimdemedes** [comment]
Done and released on npm, thanks!
