### ISSUE TITLE
GIFs open in the browser

### ISSUE THREAD

**Issue by melanke** [vdemedes/gifi#14]
It is opening a new tab of a gif in the browser each 5 seconds

**Comment by casmith** [comment]
On mac, doesn't open at all in iTerm 2. In Terminal, it opens gifs in Chrome, not in the Terminal.

**Comment by gburnett** [comment]
@melanke Are you using iTerm?

**Comment by davidgarsan** [comment]
The problem is Oh My Zsh, even with iTerm.

**Comment by eweap** [comment]
I'm on Ubuntu 14.04 with Oh-My-Zsh and Tilda and this is opening in the browser for me too.

**Comment by vadimdemedes** [comment]
GIFs inside terminal are supported only in iTerm 2.9.x (v3 beta) on OS X. In all other terminals and OSes, GIFs open in browser.

**Comment by vadimdemedes** [comment]
#15 fixed it. See the readme:

> Currently, GIFs are only displayed inline for users of iTerm2 using version 2.9 or greater. If you are not using a supported version of iTerm2, GIFs will open in your default browser.

**Comment by eweap** [comment]
I hope there will be a better compatibility accross differents terminals in the near future.

Thanks for your funny tool @vdemedes !

**Comment by vadimdemedes** [comment]
@eweap Thanks for using it! Credits for the idea go to https://github.com/sindresorhus :)

**Comment by melanke** [comment]
I am using Mac OS default Terminal
