### ISSUE TITLE
Gifi doesn't work even in iterm2 (v3 2.9.x)

### ISSUE THREAD

**Issue by TylerYang** [vdemedes/gifi#18]
Hi guys, I just installed the iterm2 (v3 2.9.x),  seems it's not working. Any ideas?
![screenshot for gifi](https://github.com/TylerYang/images/raw/master/gifi/screenshot.png)

**Comment by vadimdemedes** [comment]
Hey, I have the exact same version of iTerm 2 as you and it works here. Could it be your shell customizations?

**Comment by TylerYang** [comment]
Just remove the customizations and it is still not working. 

I will debug it later. Is it because of the cache? 
I try to install a **new module** which I've never download it before. 
After a few seconds(**longer than 20 sec**) an gif show up, and just **hang there for more than 40 seconds.**

**Comment by vadimdemedes** [comment]
Try displaying local image using `imgcat` (https://www.iterm2.com/images.html) and let me know if it works that way. If it does, I think it's just slow internet connection.

**Comment by TylerYang** [comment]
Just removed the domain configuration, everything is working now. My bad. 
Thx for the module, it bring me lots of fun! :+1:

**Comment by vadimdemedes** [comment]
:wink:
