### ISSUE TITLE
tmux 2.1, strange interaction

### ISSUE THREAD

**Issue by hhsnopek** [vdemedes/gifi#22]
## Description

I'm using the latest version of iterm2 nightly build and everything works properly in there. When I'm in my tmux session don't show up or all the images pile onto each other and at the end of the output they're cut off.
### Reference

Visual: [https://vimeo.com/157512145](https://vimeo.com/157512145)

**Comment by vadimdemedes** [comment]
Wow, weird indeed. I don't think it's related to gifi, as it just uses the official `imgcat` script by iTerm team. I googled and found [this stackoverflow question](http://unix.stackexchange.com/questions/215153/how-to-preview-image-in-tmux-in-iterm2), which is related to your situation. So apparently it does not work or does not work properly in a tmux session.

**Comment by jsatk** [comment]
Came here in search of a solution to get this working in tmux. Sad it doesn't work but glad I found an answer. Thanks.
