### ISSUE TITLE
Only display gifs for install command

### ISSUE THREAD

**Issue by ngryman** [vdemedes/gifi#6]
Hey,

Would be nice to only do that when using `install` command, so we can alias `gifi` to `npm`.

**Comment by vadimdemedes** [comment]
Was also thinking about it, good idea!

**Comment by vadimdemedes** [comment]
Done and released on npm as `gifi@1.1.0`.

**Comment by ngryman** [comment]
Noice! Thanks!

**Comment by ngryman** [comment]
@vdemedes btw, you should also mention aliasing in the readme: `alias npm='gifi'`

**Comment by vadimdemedes** [comment]
@ngryman done!

**Comment by ngryman** [comment]
@vdemedes Awesome!
