### ISSUE TITLE
Event listeners leak?

### ISSUE THREAD

**Issue by ngryman** [vdemedes/gifi#9]
Probably subscriptions to events that should not happen. If voluntary, [setMaxListeners](https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n) could help.

![image](https://cloud.githubusercontent.com/assets/892048/13334227/413b1c52-dc0b-11e5-8642-5e61d574b58a.png)

**Comment by vadimdemedes** [comment]
Thanks, fixed!
